# Generated by Django 4.0.1 on 2022-02-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_sets', models.IntegerField(blank=True, null=True)),
                ('suggested_reps', models.IntegerField(blank=True, null=True)),
                ('suggested_weight_lb', models.FloatField(blank=True, null=True)),
                ('suggested_time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockexercises', to='webapp.block')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sets', models.IntegerField(blank=True, null=True)),
                ('actual_reps', models.IntegerField(blank=True, null=True)),
                ('actual_weight_lb', models.FloatField(blank=True, null=True)),
                ('actual_time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('blockexercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockexercises', to='webapp.blockexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutlogs', to='webapp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_quantity', models.IntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutblocks', to='webapp.block')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutblocks', to='webapp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.equipmenttype')),
                ('exercise_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.exercisetype')),
            ],
        ),
        migrations.AddField(
            model_name='blockexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockexercises', to='webapp.exercise'),
        ),
    ]
