# Generated by Django 4.0.1 on 2022-01-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('equipment_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sets', models.IntegerField()),
                ('actual_reps', models.IntegerField()),
                ('actual_weight_lb', models.FloatField()),
                ('actual_time_in_seconds', models.IntegerField()),
                ('notes', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutlogs', to='webapp.block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutlogs', to='webapp.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutlogs', to='webapp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_quantity', models.IntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutcontents', to='webapp.block')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutcontents', to='webapp.workout')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.exercisetype'),
        ),
        migrations.CreateModel(
            name='BlockContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_sets', models.IntegerField(blank=True)),
                ('suggested_reps', models.IntegerField(blank=True)),
                ('suggested_weight_lb', models.FloatField(blank=True)),
                ('suggested_time_in_seconds', models.IntegerField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockcontents', to='webapp.block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockcontents', to='webapp.exercise')),
            ],
        ),
    ]
