# Generated by Django 4.0.1 on 2022-03-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='template',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='template',
        ),
    ]
