# Generated by Django 4.0.1 on 2022-03-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_block_template_remove_workout_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmenttype',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='exercisetype',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('name', 'user')},
        ),
    ]
