# Generated by Django 4.0.1 on 2022-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_block_user_alter_equipmenttype_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_normal_member',
            field=models.BooleanField(default=True),
        ),
    ]
