# Generated by Django 4.0.1 on 2022-01-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_exercise_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_time_in_seconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_weight_lb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.exercisetype'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_time_in_seconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_weight_lb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
