# Generated by Django 4.0.1 on 2022-03-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_equipmenttype_name_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockexercise',
            unique_together={('block', 'exercise', 'exercise_order')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutblock',
            unique_together={('workout', 'block', 'block_order')},
        ),
    ]
