# Generated by Django 4.0.1 on 2022-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_blockcontent_suggested_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
