# Generated by Django 4.0.1 on 2022-02-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_equipmenttype_name_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_time_in_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockcontent',
            name='suggested_weight_lb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
