# Generated by Django 4.0.1 on 2022-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_blockexercise_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutblock',
            name='block_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
