# Generated by Django 4.0.1 on 2022-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_blockcontent_suggested_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_time_in_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='actual_weight_lb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
