# Generated by Django 4.0.1 on 2022-05-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_exercise_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='webapp.workout'),
        ),
    ]
