# Generated by Django 4.0.1 on 2022-05-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_workout_updated_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blockexercise',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workoutblock',
            unique_together=set(),
        ),
    ]
